### ISSUE TITLE
这是什么错误？

### ISSUE THREAD

**Issue by pyuany** [jkchao/node-koa#7]
`/Downloads/node-koa-master/src/error/ColumnTypeUndefinedError.ts:9
        super();
        ^
ColumnTypeUndefinedError: Column type for Tag#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
    at new ColumnTypeUndefinedError (/Users/yuanpan/Downloads/node-koa-master/src/error/ColumnTypeUndefinedError.ts:9:9)
    at /Users/yuanpan/Downloads/node-koa-master/src/decorator/columns/Column.ts:119:23
    at DecorateProperty (/Users/yuanpan/Downloads/node-koa-master/node_modules/reflect-metadata/Reflect.ts:1214:35)
    at Object.decorate (/Users/yuanpan/Downloads/node-koa-master/node_modules/reflect-metadata/Reflect.ts:737:24)
    at __decorate (/Users/yuanpan/Downloads/node-koa-master/src/model/tag.ts:9:92)
    at Object.<anonymous> (/Users/yuanpan/Downloads/node-koa-master/src/model/tag.ts:21:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.m._compile (/Users/yuanpan/Downloads/node-koa-master/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/yuanpan/Downloads/node-koa-master/node_modules/ts-node/src/index.ts:403:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/yuanpan/Downloads/node-koa-master/src/controller/tag.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.m._compile (/Users/yuanpan/Downloads/node-koa-master/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/yuanpan/Downloads/node-koa-master/node_modules/ts-node/src/index.ts:403:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)`

**Comment by jkchao** [comment]
src/model/tag.ts 文件下，需要使用注释部分，不是注释的部分需要注释掉。

**Comment by pyuany** [comment]
好的  谢谢啦

**Comment by pyuany** [comment]
![image](https://user-images.githubusercontent.com/17938852/45420837-d8f7e900-b6bd-11e8-9e56-48c5230c66d0.png)
admin 这个错误呢
